### PR TITLE
Fix problem with translucent activities on Pixel devices

### PR DESCRIPTION
**Pull request by sirekanyan**
This PR should fix issue #4

### CODE REVIEW

**Comment by HotIceCream** [comment]
This activity should work in two cases: with don't keep activities and without. Also, it should be closed if the user presses the back button.

Workaround with the handler and removing callback in onResume should solve these cases. Removing it broke one of them.

**Comment by HotIceCream** [comment]
After opening a browser from BrowserLoginActivity it shouldn't finish. It should be still in Activity task and save it state. BrowserDataActivity receives redirect in the browser and recalls BrowserLoginActivity for restoring it and drop browser in Activity task. Then BrowserLoginActivity completes authorization and sends the result to application in setResult().

**Comment by sirekanyan** [comment]
Frankly, I haven't tested this fix thoroughly because of we already use sdk 2.1.1, and don't want to move back to 2.1.0. It would be nice if you could publish sources for 2.1.1 (see issue yandexmobile/yandex-login-sdk-android#3).

As I understand, we need behavior like FLAG_ACTIVITY_FORWARD_RESULT provides. To be able to pass result directly from the third activity to the first one (skipping the second activity).

But it seems if we start a browser we can't do that.

**Comment by sirekanyan** [comment]
Thanks for publishing 2.1.1
The fix breaks behavior. PR should be declined :/

**Pull request closed without merging**
